name: Build & Push VLESS Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t docker.io/virgozki/vless:latest .

      # Uncomment below when ready to push automatically
      # - name: Login to Docker Hub
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     echo "${{ secrets.DOCKER_rafael092293 }}" | docker login -u "${{ secrets.DOCKER_virgozki }}" --password-stdin

      # - name: Push to Docker Hub
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     docker push docker.io/virgozki/vless:latest

